# Generated by Django 5.2.11 on 2026-04-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='is_complete',
        ),
    ]
